spring.application.name=management-system
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7o6aub7uimc73blfhpg-a.oregon-postgres.render.com/library_db_smga?sslmode=require
spring.datasource.username=library_db_smga_user
spring.datasource.password=l4AA5rxiHcTMU6uo9PnZclSsLPDxxSfy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000