spring.application.name=management-system
# Render will look for port 10000 by default
server.port=10000
# This is a "quick fix" to permit all traffic if security is enabled
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration